### ISSUE TITLE
push to rubygems.org

### ISSUE THREAD

**Issue by drewda** [karlfreeman/middleman-sync#1]
Would you mind pushing the gem to rubygems.org for others to use?

Thanks for this project. It looks like a perfect solution to the Middleman-to-S3 problem I've been trying to solve.

**Comment by karlfreeman** [comment]
Hey @drewda, just thought I'd let you know I'll be pushing to rubygems with a working version. Feel free to let me know if anything doesn't work :)

**Comment by karlfreeman** [comment]
https://rubygems.org/gems/middleman-sync

**Comment by drewda** [comment]
Thanks, @karlfreeman. I wasn't able to make sync'ing work when I tried loading the gem from the git repo, but I'll try again soon and let you know if I have any problems.
