### ISSUE TITLE
Problem with latest version of asset_sync

### ISSUE THREAD

**Issue by carlosramireziii** [karlfreeman/middleman-sync#14]
When using version 0.5.2 of the `asset_sync` dependency, the following error occurs when syncing

```
uninitialized constant AssetSync::Storage::Mime (NameError)
```

I was able to work around this issue by adding the following to my Gemfile

```
# use a specific version of the asset_sync dependency of middleman-sync
gem 'asset_sync', '0.5.0'
```

**Comment by karlfreeman** [comment]
Looks like that was due to this commit https://github.com/rumblelabs/asset_sync/commit/bc30ab7a3428945a3c1763d320b0b0a2f1186a63. Will look in to it. Thanks for letting me know.

**Comment by nicolasgarnil** [comment]
+1 had the same problem

**Comment by karlfreeman** [comment]
Will go ahead and lock asset_sync. Thanks again

**Comment by karlfreeman** [comment]
Closed with https://github.com/karlfreeman/middleman-sync/commit/4ad3dd74226f5ad2643f905449c8bea090dce37c
