### ISSUE TITLE
S3 RRS Option

### ISSUE THREAD

**Issue by kurtisnelson** [karlfreeman/middleman-sync#15]
Can we get a configuration flag to set S3 to use reduced redundancy storage for our files?

**Comment by karlfreeman** [comment]
Good question! Looking through [asset_sync](https://github.com/rumblelabs/asset_sync) there isn't support for this kind of configuration which is a shame. However [fog](https://github.com/fog/fog) does have [support for RRS](https://github.com/fog/fog/blob/master/lib/fog/aws/models/storage/file.rb#L205). Leave this with me, this might be the final straw with having such a hard dependancy on asset_sync.

**Comment by karlfreeman** [comment]
Hope you don't mind me closing this as the 3.1 rewrite will have RRS support. I'm currently restricted by asset_sync on this so can't see this issue getting resolved without the rewrite. Feel free to open back up though if needed.
