### ISSUE TITLE
3.1 Rewrite

### ISSUE THREAD

**Issue by karlfreeman** [karlfreeman/middleman-sync#16]
Since putting middleman-sync out there its been downloaded over [15,000+ times](https://rubygems.org/gems/middleman-sync) and has had spawned from it [many](https://github.com/polleverywhere/shart) [other](https://github.com/fredjean/middleman-s3_sync) libs due mainly to missing features / functionality.

Considering that middleman-sync is essentially a shim for [asset_sync](https://github.com/rumblelabs/asset_sync) I've been quietly impressed by how much use it's been getting. However because of its shimy' nature though its difficult to [support](https://github.com/karlfreeman/middleman-sync/issues/15) [features](https://github.com/karlfreeman/middleman-sync/issues/2) [requested](https://github.com/karlfreeman/middleman-sync/issues/5) which is why middleman-sync 3.1 will be a complete re-write, sans asset_sync.

If your using / wanted to use middleman-sync please chime in on what you would like to see / whats been pain points.
## Questions
- Is anyone actually using Rackspace / Google storage?
- Would globbing dir's inside `build` to 'sync' allow for more flexibility? Eg does anyone **not** sync the whole of `/build` to :target ?
## Feature list / Requirements
- Dropping Asset_Sync, it's had a good run but maintainability and future development is too closely tied to what is an excellant **sprockets / rails** asset synchronisation library.
- S3 sync strategy with [RRS](https://github.com/karlfreeman/middleman-sync/issues/15) and CORS support
- Strategy independent sync options ( existing_remote_files / gzip_compression / ignore_files ).
- Testing, robust testing. [Cucumber seems to be the middleman choice](https://github.com/middleman/middleman-blog/tree/master/features), not sure myself. Perhaps a combination so that strategies are tested fully too. 
## Wishlist
- Perhaps change up the idea of syncing the whole `/build` but instead [support multiple build directories](https://github.com/karlfreeman/middleman-sync/issues/5) by specifying a glob for files within `/build` instead.
- Multiple :sync configurations, say your fonts are Cloudfronted on S3 but the rest live somewhere else.
- Actually use [Middleman's thor logger](https://github.com/karlfreeman/middleman-sync/issues/2)
- Other [fog](https://github.com/fog/fog) storage providers sync strategies.
- Allow for more strategies beyond fog

**Comment by fredjean** [comment]
Things that prompted me to write a couple gems:
- Keeping the update set small. Asset_Sync pushed every files under build. [fredjean/middleman-s3_sync](https://github.com/fredjean/middleman-s3_sync) tries really hard to reduce the set of files to update to the bare minimum.
- Being able to define redirects. This was particularly key for situations where case-sensitivity was an issue. Implemented in [fredjean/middleman-s3_redirect](https://github.com/fredjean/middleman-s3_redirect).

Other things to consider:
- Being able to set expiration policies on content-type. It's not quite as critical as with other apps, but it would help reduce the S3 utilisation cost.
- Integration with Cloudfront
- Automatic creation of buckets for the web site (if it isn't already present).

**Comment by andrusha** [comment]
> Is anyone actually using Rackspace / Google storage?

I do use Google storage, I guess if you're going to use `fog` as `asset_sync` does, then support for Google storage shouldn't be a big problem.

**Comment by cutemachine** [comment]
+1 for fredjean's comment.

For my usage of Middleman Sync the most important features would be
- only uploading of changed files,
- define redirect meta data, and
- define cache control meta data.

**Comment by karlfreeman** [comment]
Thanks for the feedback everybody, will look into nailing together a plan this week.

@fredjean Great feedback! Not sure how I feel about automatic creation of buckets but lets see :)

@andrusha Will most likely look at keeping `fog`. Thanks for your middleman-cloudfront, really nice to see more tooling working together.

@cutemachine Thanks for the feedback, redirect and cache-control meta data is for sure on the feature list

**Comment by fredjean** [comment]
@karlfreeman Well, at minimum a graceful recovery from a missing bucket or bad permissions would be required.

**Comment by karlfreeman** [comment]
@fredjean Missing bucket with a nice message, for sure.

**Comment by vocino** [comment]
I'd love to see some support for syncing different directories to different buckets.  For example, if I could throw /images in an images.domain.com bucket, then I could use CloudFront on that bucket specifically.

**Comment by karlfreeman** [comment]
Already ahead of you, I'm thinking of abstracting the sync to use globbing
inside the /build dir. Which would for sure allow you to sync images to one
bucket and maybe 'the rest' to another.

Will flesh out something this weekend.

**Comment by fredjean** [comment]
@vocino Would you want the globbing to be exclusive? As in send /images to bucket a, and everything else to bucket b?

**Comment by vocino** [comment]
Yeah if I had to guess I would assume most situations are like mine.  You have a primary bucket for the majority of the deliverables and then some assets specific to needing more advanced distribution.

For my own workflow, I would do be doing /images and /video but those could go to the same bucket.  Then I would use a helper to rewrite /images (on localhost) to http://cloudfront.whatever.com/images (on build).

As for the rewriting, I'm assuming you're going to let the middleman user's custom helpers handle that but it might be a nice feature to just have that work automagically.

**Comment by karlfreeman** [comment]
We're in the business of automagically. Thanks for raising custom helpers,
something I hadn't thought too much about. I'll look in to what is
currently available in middleman-sprockets when it comes to specifying
multiple locations.

**Comment by geoffreywiseman** [comment]
I just switched to s3_sync today, mostly because I agree that it seems like middleman-sync, which I'd definitely continue to use if s3_sync wasn't there, uploads lots of things to S3 that haven't been updated, which seems excessive. That feature alone would probably bring me back into the fold. Many of the other things above sound nice, but aren't currently a big deal to me (although they could be, at some point, of course).

**Comment by karlfreeman** [comment]
@geoffreywiseman Thanks for the feedback. :+1: Working on getting something together real soon.

**Comment by karlfreeman** [comment]
Just thought I'd drop in and say that I've been chipping away at [multi_sync](https://github.com/karlfreeman/multi_sync) and slowly getting to a point where I'll be integrating it with `middleman-sync`. I've still got a lot of work left such as cache-control, acl, storage-class and some other bits but progress is being made.

Part of the work (if anyone is interested) has been making it work with Rails 3.2 / 4 as a replacement for `asset_sync`. Would love it if anyone is brave enough to give it a whirl at some point

**Comment by manuelmeurer** [comment]
Looks awesome! Let me know what exactly you need help with and I'll try to help out!

**Comment by sandstrom** [comment]
I agree, `multi_sync` looks really awesome! :sailboat: 

(Regarding your question on top, I think few are using Rackspace/Google, so I'd say stick to S3 to begin with)

**Comment by karlfreeman** [comment]
@sandstrom Going to start with an [S3 target](https://github.com/karlfreeman/multi_sync/blob/master/lib/multi_sync/targets/aws_target.rb) to begin with however Its just one strategy ontop of a [inhereited target](https://github.com/karlfreeman/multi_sync/blob/master/lib/multi_sync/target.rb) so should be simple to venture onto Rackspace / Google.

and thanks! :boat:

**Comment by karlfreeman** [comment]
#### Updates :)

I'm really looking forward to being able to demo to you all the next version of middleman-sync and its integrations with the shiny [multi_sync](https://github.com/karlfreeman/multi_sync). The ability to define multiple targets and sources in multi_sync allows for some interesting use cases that I've been brainstorming.

#### Question

Out of the below which of the use cases blows your mind the most?

#### Language independant deploys Using [Middleman's i18n](http://middlemanapp.com/advanced/localization)

Given the same list of `locales` as Middleman, synchronise each source directory to a different target. These different targets could be setup as different [static websites on S3](http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html).

``` ruby
locales = [:en, :es, :fr]

MultiSync.run do

  locales.each do | locale |

    source "#{locale}_source" {
      :type => :local,
      :source_dir => "/build/#{locale}",
      :targets => "#{locale}_target"
    }

    target "#{locale}_target"  {
      :type => :aws,
      :target_dir => "#{locale}",
      :credentials => {
      # :region => "us-east-1", # MultiSync has built in .fog support so these could be abstracted away
      # :aws_access_key_id => "super_secret", # MultiSync has built in .fog support so these could be abstracted away
      # :aws_secret_access_key => "super_secret" # MultiSync has built in .fog support so these could be abstracted away
    }
    }

  end

end
```

#### Optimized asset delivery

A `source` allows for an `include` glob and an `exclude` glob meaning we can whittle out different asset types and send them to different targets (which in turn could be Cloudfront`ed S3 buckets). Mix in a helper as per @vocino suggestion and you've got yourself a nifty way to optimize certain site resources.

``` ruby
MultiSync.run do

  source :videos {
    :type => :local,
    :source_dir => "/build",
    :include => "*.{mp4,mpg,mov}"
    :targets => :videos
  }

  source :images {
    :type => :local,
    :source_dir => "/build",
    :include => "*.{jpg,gif,png}"
    :targets => :images
  }

  source :www {
    :type => :local,
    :source_dir => "/build",
    :exclude => "*.{mp4,mpg,mov,jpg,gif,png}"
    :targets => :www
  }

  target :videos, {
    :type => :aws,
    :target_dir => "s3_video_bucket",
    :credentials => {
      # :region => "us-east-1", # MultiSync has built in .fog support so these could be abstracted away
      # :aws_access_key_id => "super_secret", # MultiSync has built in .fog support so these could be abstracted away
      # :aws_secret_access_key => "super_secret" # MultiSync has built in .fog support so these could be abstracted away
    }
  }

  target :images, {
    :type => :aws,
    :target_dir => "s3_image_bucket",
    :credentials => {
      # :region => "us-east-1", # MultiSync has built in .fog support so these could be abstracted away
      # :aws_access_key_id => "super_secret", # MultiSync has built in .fog support so these could be abstracted away
      # :aws_secret_access_key => "super_secret" # MultiSync has built in .fog support so these could be abstracted away
    }
  }

  target :www, {
    :type => :aws,
    :target_dir => "s3_deploy_bucket",
    :credentials => {
      # :region => "us-east-1", # MultiSync has built in .fog support so these could be abstracted away
      # :aws_access_key_id => "super_secret", # MultiSync has built in .fog support so these could be abstracted away
      # :aws_secret_access_key => "super_secret" # MultiSync has built in .fog support so these could be abstracted away
    }
  }

end
```

#### Multi S3 region deployments

A source can be synchronised against multiple targets (in parallel). Each target could be the same assets but in different regions allowing for region redundancy for a static site! Combine that with [Route 53's multi-region latency based routing](http://aws.typepad.com/aws/2012/03/latency-based-multi-region-routing-now-available-for-aws.html) and you've got yourself a simply riduculuously quick static site.

``` ruby
regions = ["eu-west-1", "us-west-1", "us-west-2", "ap-southeast-1", "ap-northeast-1", "sa-east-1"]

MultiSync.run do

  source :build {
    :type => :local,
    :source_dir => "/build",
    :targets => regions
  }

  regions.each do | region_name |

    target region_name {
      :type => :aws,
      :credentials => {
        :region => region_name,
      # :aws_access_key_id => "super_secret", # MultiSync has built in .fog support so these could be abstracted away
      # :aws_secret_access_key => "super_secret" # MultiSync has built in .fog support so these could be abstracted away
      }
    }

  end

end
```

_sorry for the huge, huge comment_

Thanks!

**Comment by sandstrom** [comment]
Language independant deploys sounds awesome! Especially useful if the different locales are under different domains, e.g. `foo.de` and `foo.co.uk`

Optimized asset delivery also sounds useful, though I've got little experience with that type of deploys.

I'll track this closely as things progresses!

**Comment by karlfreeman** [comment]
@sandstrom Thanks for your thoughts. I think the language independent deploys has a real tangible feel to it particularly if used in the way you describe. A couple country code TLD's and Middleman's i18n really could be a very interesting way to write static sites in multi languages.

**Comment by manuelmeurer** [comment]
What is the status of the rewrite?
Anything that you need help testing or developing?
Looking forward to the new version! :smiley_cat:

**Comment by karlfreeman** [comment]
@manuelmeurer Will let you know asap as to when I've got some more progress. middleman-sync will be the trail blazer for multi_sync. I'm currently using it at my current workplace and it seems to be doing a great job (preview of the `:verbose` mode set to true below).

![screen shot 2013-08-29 at 20 20 10](https://f.cloud.github.com/assets/139095/1052623/796d7bcc-10e0-11e3-8b73-958bad25f45d.png)

Its coming! and its much, much faster! :smile: 

p.s you'll notice that one of the jobs finishes before we've even started to fetch them back from the futures, its simply that quick when on AWS boxes.

**Comment by karlfreeman** [comment]
Actually bit of an update around syntax. I'm not sold on it 100% but what about something below as a 'bridge' between Middleman and MutiSync

``` ruby

activate :sync do |config|
  config.logging = true
  config.verbose = true
  config.force = true
  config.run_on_build = true
  config.sync_outdated_files = true
  config.delete_abandoned_files = true
  config.upload_missing_files = true
  config.target_pool_size = 8
  config.max_sync_attempts = 1
end

# This could become obsolete if we assume that 'build' is always a 'source'
activate :sync_source do |source|
  source.name = :public
  source.type = :local
  source.source_dir = File.expand_path(File.join(ENV['MM_ROOT'], 'build')) # This could have a short-hand at some point...
  source.targets = [ :www ]
end

activate :sync_target do |target|
  target.name = :www
  target.type = :aws
  target.target_dir = 's3_bucket'
  # target.destination_dir = 'an_optional_directory_inside_your_aws_bucket'
  target.credentials = {
      :region => 'us-east-1',
      :aws_access_key_id => 'super_secret',
      :aws_secret_access_key => 'super_secret'
  }
end
```

My gripes with the current way of doing things is. 1) That you have specify a 'source' even though it could be implied that its simply Middleman's build folder. 2) How you specify which targets a source should be synced against by manipulating an array of 'targets' which have to match the 'name's of the targets.

Thoughts?

**Comment by manuelmeurer** [comment]
I think the basic version should just have one `activate :sync` block. As you said, the source should by default (if not defined otherwise) be the `build` folder.
Would something like this work?

``` ruby
activate :sync do |config|
  config.logging = true                   # Set sane default for all of these                        
  config.verbose = true                   # Set sane default for all of these      
  config.force = true                     # Set sane default for all of these    
  config.run_on_build = true              # Set sane default for all of these            
  config.sync_outdated_files = true       # Set sane default for all of these                  
  config.delete_abandoned_files = true    # Set sane default for all of these                      
  config.upload_missing_files = true      # Set sane default for all of these                    
  config.target_pool_size = 8             # Set sane default for all of these            
  config.max_sync_attempts = 1            # Set sane default for all of these              
  config.target = :s3
  config.target.credentials = {
    :region => 'us-east-1',
    :aws_access_key_id => 'super_secret',
    :aws_secret_access_key => 'super_secret'
  }
end
```

I realize you can probably have multiple sources and targets in multi_sync but this would probably be the most common use case.

**Comment by sandstrom** [comment]
I just noticed that `asset_sync` (which will be replaced by multi_sync) sets the permission of all files on S3 to public by default. I think multi_sync does the right thing already, setting it to private by default, but just wanted to highlight the issue since it's partially related to middleman-sync.

In short, I think private by default is good because:
1. people typically use bucket policies instead of ACL, or they use CloudFront access identities, and 
2. it's good security practice to have secure defaults.

**Comment by manuelmeurer** [comment]
I see you started with a 4.0 rewrite... will this supersede the 3.1 rewrite?

**Comment by karlfreeman** [comment]
@manuelmeurer Wow. Justs saw this pop up as I was writing... well done.

Yes. I've `1.0`'d [`multi_mime`](https://github.com/karlfreeman/multi_mime) (which was part of the work for `multi_sync`) and [`multi_sync`](https://github.com/karlfreeman/multi_sync) is at a stage where I'm comfortible letting people try it out.

As Middleman's master is now pegged at [`4.0.0.pre`](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/version.rb#L4) I figured it was only apt that the replacement of [`asset_sync`](https://github.com/rumblelabs/asset_sync) in `middleman-sync` followed the same style of release.

Aside from `gzip_compression` all previous settings are being catered for so it should be a straight gem upgrade. Of course though, `multi_sync` has a lot more options under the hood and it would be advisable to not use the "old" configuration style.

It's been a long slog but its getting closer. Thanks for waiting :+1:.

**Comment by karlfreeman** [comment]
There's still a bit more work to do. Writing tests for 4.0 `middleman-sync` and finishing up the docs for both `middleman-sync` and `multi_sync` but I'm really focusing on finishing things over the next few days.

I'm going to keep this issue open until I've got a 4.0.0.pre out for testing.

**Comment by manuelmeurer** [comment]
Awesome, thanks for your work! Let me/us know when there is something to be tested.

**Comment by karlfreeman** [comment]
Just putting together some examples for `multi_sync`.

For instance: 
- [Here's the example config.rb file with `asset_sync` compatability](https://github.com/karlfreeman/multi_sync-middleman/blob/middleman-3-asset_sync-compatibility/config.rb)
- [Here's the example config.rb file without `multi_sync` configuration (which is still a WIP)](https://github.com/karlfreeman/multi_sync-middleman/blob/middleman-3/config.rb).

**Comment by manuelmeurer** [comment]
Hope these are not real AWS credentials in both those files...? :scream_cat:

**Comment by karlfreeman** [comment]
@manuelmeurer locked down `IAM` based ones :+1:. Will cycle out when I've got `multi_sync` `1.0` finished.

**Comment by sandstrom** [comment]
Awesome progress! :smile:

**Comment by karlfreeman** [comment]
@sandstrom Thanks. Just managed to get a [full green build](https://travis-ci.org/karlfreeman/multi_sync/builds/20457470) on `multi_sync` so should be able to put a pre-release together for `middleman-sync` real soon.

**Comment by sandstrom** [comment]
:fireworks: :balloon:
