### ISSUE TITLE
Asset_Sync problem with latest release of Middleman (3.0.12)

### ISSUE THREAD

**Issue by dpfranklin** [karlfreeman/middleman-sync#18]
Upon middleman build with the following config:

```
activate :sync do |sync|
  sync.fog_provider = 'AWS' 
  sync.fog_directory = ENV['BUCKET_NAME'] 
  sync.fog_region = 'us-east-1'
  sync.aws_access_key_id = ENV['AWS_ACCESS_KEY'] 
  sync.aws_secret_access_key = ENV['AWS_SECRET_KEY']
  sync.existing_remote_files = 'delete'
  sync.gzip_compression = true 
  sync.after_build = true
end
```

 using latest middleman release (3.0.12) and latest middleman_sync, the follow error occurs:

```
$ middleman build
/Users/david/.rvm/gems/ruby-1.9.3-p392/gems/asset_sync-0.5.4/lib/asset_sync/config.rb:99:in `yml_path': undefined method `root' for Rails:Module (NoMethodError)
```

Full trace here:  https://gist.github.com/dpfranklin/5052057

**Comment by karlfreeman** [comment]
Sorry for the delay in getting on this. Will look into it today.

**Comment by andrusha** [comment]
:+1: I'm having the same problem

**Comment by andrusha** [comment]
Reverting back to 3.0.9 actually helps

```
gem "middleman", "3.0.9"
gem "middleman-sync", "3.0.9"
```

**Comment by kurtisnelson** [comment]
+1
Note just locking the middleman-sync version to 3.0.9 doesn't fix it.

**Comment by dpfranklin** [comment]
This appears have been made an issue by this commit to AssetSync:

https://github.com/rumblelabs/asset_sync/commit/06af52e56482142d77a25fab5092e4dec11732ed

The change is to lib/asset_sync/config.rb:

```
def yml
  @yml ||= YAML.load(ERB.new(IO.read(yml_path)).result)[Rails.env] rescue nil || {}
end
```

to:

```
def yml
  begin
    @yml ||= YAML.load(ERB.new(IO.read(yml_path)).result)[Rails.env] rescue nil || {}
  rescue Psych::SyntaxError
    @yml = {}
  end
end
```

Has this been silently failing all along because this fails?

```
def yml_path
  Rails.root.join("config", "asset_sync.yml").to_s
end
```

**Comment by 0x00b1** [comment]
Thanks for investigating @dpfranklin.

**Comment by karlfreeman** [comment]
So @dpfranklin's is bang on. Even more bang on is @2a6U37Nn's pull request to asset_sync. I'd advise for now to use `gem 'asset_sync', :git => 'git://github.com/2a6U37Nn/asset_sync.git` in your Gemfile which should solve the problem till it 'possibly' gets merged in asset_sync.

Roll on #16

**Comment by stoplion** [comment]
Is this still the right way to fix this? I can't seem to get this to work.
