### ISSUE TITLE
You need to activate the sync extension in config.rb

### ISSUE THREAD

**Issue by stoplion** [karlfreeman/middleman-sync#19]
Filled in S3 credentials in config.rb and manually running middleman sync, and am getting a "You need to activate the sync extension in config.rb".

```
activate :sync do |sync|
  sync.fog_provider = ENV['FOG_DIRECTORY'] # Your storage provider
  sync.fog_directory = 'my_awesome_bucket' # Your bucket name
  sync.fog_region = 'us-east-1' # The region your storage bucket is in (eg us-east-1, us-west-1, eu-west-1, ap-southeast-1 )
  sync.aws_access_key_id = ENV['AWS_ACCESS_KEY_ID'] # Your Amazon S3 access key
  sync.aws_secret_access_key = ENV['AWS_SECRET_ACCESS_KEY'] # Your Amazon S3 access secret
  sync.existing_remote_files = 'delete' # What to do with your existing remote files? ( keep or delete )
  # sync.gzip_compression = false # Automatically replace files with their equivalent gzip compressed version
  # sync.after_build = false # Disable sync to run after Middleman build ( defaults to true )
end
```

Using Foreman and .env file to fill in the secret/key/provider.

**Comment by karlfreeman** [comment]
What version of middleman-sync are you using?

**Comment by stoplion** [comment]
I'm using 3.0.9.

```
gem "middleman", "~> 3.0.11"
gem "middleman-blog", "~> 3.1.1"
gem "middleman-blog-editor"
gem "middleman-sync", "~> 3.0.9"
```

**Comment by karlfreeman** [comment]
I can't seem to reproduce the problem. Whats your config.rb and Gemfile.lock look like?

Essentially [this](https://github.com/karlfreeman/middleman-sync/blob/master/lib/middleman-sync/commands.rb#L24) is whats printing the message. Is the `ENV['FOG_DIRECTORY']` actually coming through?

**Comment by stoplion** [comment]
ENV['FOG_DIRECTORY'] is coming up blank. `Fog provider can't be blank (AssetSync::Config::Invalid)`
Guess its not picking up .env file. Would the way to do it, be to just preface the middleman command with credentials?

```
FOG_DIRECTORY=example-staging middleman build
```

**Comment by stoplion** [comment]
Got it to work. Stuck this is a Procfile..

```
build: bundle exec middleman build
```

Ran `foreman start` Foreman picked up .env vars and it uploaded perfectly.

**Comment by karlfreeman** [comment]
Glad to see this closed :+1: thanks.
