### ISSUE TITLE
Railties - Related Error on Sync

### ISSUE THREAD

**Issue by stationkeeping** [karlfreeman/middleman-sync#20]
Syncing or building Throws the following:

`/Users/username/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/asset_sync-0.5.4/lib/asset_sync/railtie.rb:1:in`<top (required)>': uninitialized constant Rails::Railtie (NameError)`

```
asset_sync (0.5.4) 
middleman-sync (3.0.9)
```

Tried including Railties explicitly in the Gemfile, but this leads to a tangle of gem dependency errors.

```
activate :sync do |sync|
  sync.fog_provider = 'AWS' # Your storage provider
  sync.fog_directory = ENV['AWS_BUCKET'] # Your bucket name
  sync.fog_region = ENV['AWS_REGION'] # The region your storage bucket is in (eg us-east-1, us-west-1, eu-west-1, ap-southeast-1 )
  sync.aws_access_key_id = ENV['AWS_ACCESS_KEY_ID'] # Your Amazon S3 access key
  sync.aws_secret_access_key = ENV['AWS_SECRET_ACCESS_KEY'] # Your Amazon S3 access secret
  sync.existing_remote_files = 'keep' # What to do with your existing remote files? ( keep or delete )
  sync.after_build = true # Disable sync to run after Middleman build ( defaults to true )
end
```

**Comment by isaksky** [comment]
+1.

**Comment by mparramont** [comment]
+1 here

**Comment by Undistraction** [comment]
+1

**Comment by karlfreeman** [comment]
I think [this](https://github.com/middleman/middleman-sprockets/commit/ef92bfc2acd99a4b894a6128f7d65e18c5fc365e) might be the suspect problem. Try upgrading to `middleman-sprockets 3.0.10`

**Comment by mparramont** [comment]
Yup,  adding the following to my Gemfile:

```
gem 'middleman-sprockets', '-> 3.0.10'
```

fixed the problem. Thanks!

**Comment by stationkeeping** [comment]
This looks good.
