### ISSUE TITLE
Error when syncing to S3

### ISSUE THREAD

**Issue by ronnyandre** [karlfreeman/middleman-sync#28]
I'm getting an error when running `middleman sync` to sync with S3:

```
AssetSync: Syncing.
Invalid Excon request keys: :scheme, :host
```

Files are uploading, but the error still shows up.

**Comment by karlfreeman** [comment]
Looks like this is stemming from [Fog](https://github.com/fog/fog/issues/2284) the underlying lib that asset_sync uses.

**Comment by manuelmeurer** [comment]
Just ran into the same error, updating fog to 1.18.0 fixed it.
