### ISSUE TITLE
multiple deployment sites/versions?

### ISSUE THREAD

**Issue by drewda** [karlfreeman/middleman-sync#5]
Hi @karlfreeman,

I'd like to start deploying my site in a two-stage process: First to a staging server for others within my organization to review, and then to a production server. Do you have any suggestions on how to do this?

Thanks!

**Comment by karlfreeman** [comment]
Looking over middleman the concept of 'environments' doesn't exist ( [its used more like what middleman is doing](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/application.rb#L88) ) which would lead me to look at doing this within the config.rb. Perhaps @tdreyno has some thoughts but I havent looked in to it myself.

Would simply changing some of middleman-sync options be enough for your needs? ( eg changing the fog directory per environment )

**Comment by drewda** [comment]
Yes, being able to specify the fog directory per environment would be great.

Thanks for considering this!

**Comment by tdreyno** [comment]
I usually use ENV variable for different deploy targets.

```
TARGET=staging middleman build
```

Then use `ENV['TARGET']` in my code.

**Comment by karlfreeman** [comment]
Much better solution. Thanks for the input.
