### ISSUE TITLE
Only accepts `sync.after_build = true`

### ISSUE THREAD

**Issue by max** [karlfreeman/middleman-sync#6]
Hey,
I just tried using `middelman-sync` and it struck me as odd that `sync.after_build` needs to be `true` to work. Is this intentional? Am I missing something?

**Comment by karlfreeman** [comment]
When I was looking in to hooking AssetSync and Middleman together it was suggested that [middleman build is `false` by default](http://forum.middlemanapp.com/discussion/comment/149#Comment_149). Its a good catch that its not obvious. I'll add to the [README.md](https://github.com/karlfreeman/middleman-sync/blob/master/README.md) about this. Thanks :)

**Comment by ghost** [comment]
I had this same problem. I don't know if the fix targets the issue correctly. Unless sync.after_build is set to true the syncing does not work at all, under any circumstance. This includes having it commented out (and defaulting to false). All that happens is an error message that reads "You need to activate the sync extension in config.rb" shows up on the command line. A person has to explicitly set the variable to true to get it to work even if you're trying to use the sync manually after running a build command.

**Comment by karlfreeman** [comment]
@dworzanski I think now that a couple people have had a look at configuring Middleman-Sync and assumed that the after_build is true by default I'll swap it around. When I was putting it together I did'nt have much to go on with 'standards' for extensions. Thanks :)

**Comment by max** [comment]
@karlfreeman I don't think 8ab6e19 addresses the issue. The issue is not wether `sync` should run `after_build` or not. The issue is that unless you set it to `true` the Middleman extension is just not registered. Setting `after_build` to `false` and **manually** running `middleman sync` results in:

```
You need to activate the sync extension in config.rb
```

**Comment by karlfreeman** [comment]
@max This commit 73337c514c578aa91d4f06ae5aabe2ed8c3d6b86 which got snuck in before. Should sort out the problem with the `sync` command not working without after_build. I've bumped the gem so you should be able to update, pull it down and see.

**Comment by max** [comment]
@karlfreeman You rock, my bad. It works as expected. :cake:

**Comment by karlfreeman** [comment]
@max No worries :+1:
