### ISSUE TITLE
Ignores sync.after_build setting

### ISSUE THREAD

**Issue by ryanwood** [karlfreeman/middleman-sync#9]
When I run `middleman build`, it syncs regardless of the after_build setting in my config. I've set it to false, but it continues to sync on each build. Any ideas?

```
activate :sync do |sync|
  sync.fog_provider = 'AWS' # Your storage provider
  ...
  sync.after_build = false
end
```

I simply appended this config block to the bottom of the config.rb file. Does it need to be nested under `configure :build do`?

**Comment by karlfreeman** [comment]
Sorry about that, must of snuck through when I changed https://github.com/karlfreeman/middleman-sync/issues/6
